// Gepárd-FEN B2B webshop — adatmodell
// Forrás: gepardfen.hu kategóriák + reális kitalált cikkszámok

const GF_CATEGORIES = [
  {
    id: "fenyszorok",
    name: "Fényszórók",
    icon: "headlight",
    count: 247,
    sub: ["Halogén", "LED", "Munkalámpák", "Pótfények", "Vontató fényszórók"],
  },
  {
    id: "fenyhidak",
    name: "Fényhidak",
    icon: "lightbar",
    count: 64,
    sub: ["LED fényhidak", "Halogén fényhidak", "Tartók, konzolok"],
  },
  {
    id: "vonofejek",
    name: "Vonófejek",
    icon: "hitch",
    count: 138,
    sub: ["Gömbös", "Csapos D40", "Csapos D50", "Pótkocsi vonóhorog", "Mech. alkatrészek"],
  },
  {
    id: "hengeres",
    name: "Hengeres alkatrészek",
    icon: "cylinder",
    count: 92,
    sub: ["Hidraulika hengerek", "Pneumatikus", "Tömítések"],
  },
  {
    id: "hibrid",
    name: "Hibrid alkatrészek",
    icon: "hybrid",
    count: 41,
    sub: ["Vezérlés", "Kapcsolók"],
  },
  {
    id: "rakomanyrog",
    name: "Rakományrögzítők",
    icon: "strap",
    count: 88,
    sub: ["Hevederek", "Kötelek", "Sarokvédők"],
  },
  {
    id: "prizmak",
    name: "Prizmák, helyzetjelzők",
    icon: "prism",
    count: 156,
    sub: ["LED helyzetjelző", "Prizmák", "Visszajelzők"],
  },
  {
    id: "zsanerok",
    name: "Zsanérok, oldalfalkapcsok",
    icon: "hinge",
    count: 73,
    sub: ["Zsanérok", "Oldalfalkapcsok", "Rögzítők"],
  },
  {
    id: "trabant",
    name: "Trabant alkatrészek",
    icon: "trabant",
    count: 184,
    sub: ["Karosszéria", "Motor", "Futómű", "Elektromos"],
    legacy: true,
  },
  {
    id: "avia",
    name: "AVIA alkatrészek",
    icon: "truck",
    count: 122,
    sub: ["Karosszéria", "Motor", "Futómű"],
    legacy: true,
  },
  {
    id: "egyebek",
    name: "Egyebek",
    icon: "more",
    count: 211,
    sub: ["Tartozékok", "Szerszámok"],
  },
];

const GF_BRANDS = [
  { name: "WESEM", country: "PL", role: "Magyarországi képviselet" },
  { name: "POLMO", country: "PL", role: "Képviselet" },
  { name: "SPP", country: "PL", role: "Partner" },
  { name: "Fristom", country: "PL", role: "Partner" },
  { name: "Rywal", country: "PL", role: "Partner" },
  { name: "Sertplas", country: "TR", role: "Partner" },
  { name: "Rainbow", country: "BG", role: "Partner" },
  { name: "SFK", country: "BG", role: "Partner" },
  { name: "Garant", country: "BG", role: "Partner" },
  { name: "Autocommers", country: "BG", role: "Partner" },
  { name: "Korchakov", country: "BG", role: "Partner" },
];

// Termékek — minden cikkszám reális szerkezetű
const GF_PRODUCTS = [
  {
    sku: "WSM-RE2-12V",
    name: "WESEM RE.22500 munkalámpa LED 12V",
    cat: "fenyszorok",
    sub: "Munkalámpák",
    brand: "WESEM",
    listPrice: 18900,
    unit: "db",
    moq: 1,
    stock: 142,
    eta: "Készleten",
    badge: "Bestseller",
    specs: { "Feszültség": "12V", "Teljesítmény": "27W", "Lumen": "1800 lm", "IP": "IP67", "Foglalat": "LED integrált" },
  },
  {
    sku: "WSM-HM3-24V",
    name: "WESEM HM3.07000 főfényszóró H4 24V",
    cat: "fenyszorok",
    sub: "Halogén",
    brand: "WESEM",
    listPrice: 24500,
    unit: "db",
    moq: 1,
    stock: 38,
    eta: "Készleten",
    specs: { "Feszültség": "24V", "Foglalat": "H4", "Átmérő": "Ø178 mm", "Homologizáció": "E-jel" },
  },
  {
    sku: "FRS-272-LED",
    name: "Fristom FT-272 LED helyzetjelző sárga",
    cat: "prizmak",
    sub: "LED helyzetjelző",
    brand: "Fristom",
    listPrice: 3450,
    unit: "db",
    moq: 2,
    stock: 612,
    eta: "Készleten",
    badge: "Akció",
    discount: 15,
    specs: { "Feszültség": "12-24V", "Szín": "Borostyán", "IP": "IP68", "Hossz": "98 mm" },
  },
  {
    sku: "POL-VF-D50",
    name: "POLMO Vonófej D50 csapos 40t",
    cat: "vonofejek",
    sub: "Csapos D50",
    brand: "POLMO",
    listPrice: 89400,
    unit: "db",
    moq: 1,
    stock: 7,
    eta: "Készleten",
    specs: { "Csaptípus": "D50", "Húzóerő": "40 t", "Tömeg": "12.4 kg", "Csavarkép": "160×100" },
  },
  {
    sku: "RYW-LB-180",
    name: "Rywal LED fényhíd 180W kombi sugár",
    cat: "fenyhidak",
    sub: "LED fényhidak",
    brand: "Rywal",
    listPrice: 67800,
    unit: "db",
    moq: 1,
    stock: 0,
    eta: "Várható: máj. 14.",
    specs: { "Teljesítmény": "180W", "Lumen": "16200 lm", "Hossz": "1062 mm", "IP": "IP69K" },
  },
  {
    sku: "SPP-HEV-50",
    name: "SPP Rögzítő heveder 50mm 5t racsnis",
    cat: "rakomanyrog",
    sub: "Hevederek",
    brand: "SPP",
    listPrice: 6200,
    unit: "db",
    moq: 4,
    stock: 320,
    eta: "Készleten",
    specs: { "Szélesség": "50 mm", "Húzóerő": "5000 daN", "Hossz": "10 m" },
  },
  {
    sku: "WSM-RE2-FOG",
    name: "WESEM RE.13620 ködlámpa H3 12/24V",
    cat: "fenyszorok",
    sub: "Halogén",
    brand: "WESEM",
    listPrice: 14200,
    unit: "db",
    moq: 1,
    stock: 56,
    eta: "Készleten",
    specs: { "Feszültség": "12/24V", "Foglalat": "H3", "Ø": "129 mm" },
  },
  {
    sku: "SRT-ZSA-160",
    name: "Sertplas zsanér 160 mm cinkezett",
    cat: "zsanerok",
    sub: "Zsanérok",
    brand: "Sertplas",
    listPrice: 2480,
    unit: "db",
    moq: 10,
    stock: 1840,
    eta: "Készleten",
    specs: { "Hossz": "160 mm", "Anyag": "acél, cinkezett", "Csapátmérő": "Ø10 mm" },
  },
  {
    sku: "FRS-415-PRZ",
    name: "Fristom FT-415 prizma kerek piros",
    cat: "prizmak",
    sub: "Prizmák",
    brand: "Fristom",
    listPrice: 690,
    unit: "db",
    moq: 10,
    stock: 4200,
    eta: "Készleten",
    badge: "Tömegáru",
    specs: { "Átmérő": "Ø60 mm", "Szín": "piros", "Rögzítés": "öntapadó / csavar" },
  },
  {
    sku: "TRB-LE-3601",
    name: "Trabant 601 hátsó lámpa komplett",
    cat: "trabant",
    sub: "Elektromos",
    brand: "PMO",
    listPrice: 8900,
    unit: "db",
    moq: 1,
    stock: 24,
    eta: "Készleten",
    specs: { "Modell": "601", "Oldal": "univerzális" },
  },
  {
    sku: "AVI-V-CSP-22",
    name: "AVIA féktárcsa első Ø280",
    cat: "avia",
    sub: "Futómű",
    brand: "Garant",
    listPrice: 15600,
    unit: "db",
    moq: 1,
    stock: 12,
    eta: "Készleten",
    specs: { "Átmérő": "280 mm", "Vastagság": "22 mm" },
  },
  {
    sku: "WSM-RE2-BEA",
    name: "WESEM RE.13510 távolsági fényszóró",
    cat: "fenyszorok",
    sub: "Halogén",
    brand: "WESEM",
    listPrice: 21800,
    unit: "db",
    moq: 1,
    stock: 18,
    eta: "Készleten",
    specs: { "Feszültség": "12/24V", "Foglalat": "H1", "Ø": "183 mm" },
  },
];

// B2B partner-szintek
const GF_TIERS = {
  guest:    { label: "Vendég",        discount: 0,    color: "#94a3b8" },
  bronze:   { label: "Bronz partner", discount: 0.08, color: "#b45309" },
  silver:   { label: "Ezüst partner", discount: 0.14, color: "#64748b" },
  gold:     { label: "Arany partner", discount: 0.22, color: "#d97706" },
  platinum: { label: "Platina partner", discount: 0.30, color: "#0f172a" },
};

// Mennyiségi kedvezmény sávok (a partner alapkedvezményén FELÜL)
const GF_QTY_TIERS = [
  { from: 1, extra: 0 },
  { from: 5, extra: 0.03 },
  { from: 20, extra: 0.06 },
  { from: 50, extra: 0.10 },
];

const GF_SAMPLE_PARTNER = {
  company: "AutóTechnik Bt.",
  contact: "Kovács Péter",
  email: "kovacs.peter@autotechnik.hu",
  partnerId: "P-2189",
  tier: "gold",
  creditLimit: 2_500_000,
  creditUsed: 412_300,
  paymentTerms: "Nettó 30 nap",
  recentOrders: 47,
};

Object.assign(window, {
  GF_CATEGORIES, GF_BRANDS, GF_PRODUCTS, GF_TIERS, GF_QTY_TIERS, GF_SAMPLE_PARTNER,
});
